[package]
name = "etcd-bin-vendored"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
authors.workspace = true

[dependencies]
etcd-bin-vendored-linux-amd64   = { workspace = true, optional = true }
etcd-bin-vendored-linux-arm64   = { workspace = true, optional = true }
etcd-bin-vendored-linux-ppc64le = { workspace = true, optional = true }
etcd-bin-vendored-darwin-amd64  = { workspace = true, optional = true }
etcd-bin-vendored-windows-amd64 = { workspace = true, optional = true }

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
etcd-bin-vendored-linux-amd64 = { workspace = true }

[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))'.dependencies]
etcd-bin-vendored-linux-arm64 = { workspace = true }

[target.'cfg(all(target_os = "linux", target_arch = "powerpc64"))'.dependencies]
etcd-bin-vendored-linux-ppc64le = { workspace = true }

[target.'cfg(all(target_os = "macos", target_arch = "x86_64"))'.dependencies]
etcd-bin-vendored-darwin-amd64 = { workspace = true }


[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
etcd-bin-vendored-windows-amd64 = { workspace = true }

[target.'cfg(all(target_os = "windows", target_arch = "aarch64"))'.dependencies]
etcd-bin-vendored-windows-amd64 = { workspace = true }

[features]
default = []
linux-x86_64 = ["dep:etcd-bin-vendored-linux-amd64"]
linux-aarch64 = ["dep:etcd-bin-vendored-linux-arm64"]
linux-powerpc64 = ["dep:etcd-bin-vendored-linux-ppc64le"]
macos-x86_64 = ["dep:etcd-bin-vendored-darwin-amd64"]
windows-x86_64 = ["dep:etcd-bin-vendored-windows-amd64"]
